### ISSUE TITLE
No xib or interface builder

### ISSUE THREAD

**Issue by axelpart** [devxoul/RxViewController#10]
I wanted to ask if anyone tried to use it in a UIController without a .xib or interface builder screen. I am trying to use it on custom classes but after subscribing to any method nothing is happening.

**Comment by devxoul** [comment]
@axelpart can you share your code?

**Comment by axelpart** [comment]
@devxoul sorry for opening the issue. I created a test project and everything works as expected. I think that there is an issue on my other project setup somewhere. Please feel free to close the issue.
