### ISSUE TITLE
Move To Community

### ISSUE THREAD

**Issue by bobgodwinx** [devxoul/RxViewController#6]
### Currently 
This repo. is living currently outside the @rxCommunity repos. It would be nice to move the repository to https://github.com/RxSwiftCommunity where more people can contribute and also see it. Let me know what you think thanks

**Comment by devxoul** [comment]
@bobgodwinx, thanks for suggestion. However, I'm kind of tired of having responsibilities in community support. ([There was an issue before](https://github.com/RxSwiftCommunity/RxKeyboard/issues/45)) I think it would be better to keep my RxSwift extension repositories in my account.

**Comment by bobgodwinx** [comment]
@devxoul I can understand how you feel from the thread and I would say that it was really tricky get a sense of what is happening on the issue. Opensource  can be sometimes frustrating because everyone has he/her own opinion. I've seen that you made a lot of contributions to the RxSwift community and we really do appreciate the fact that you keepon contributing to this community. Having said that, I don't want you to feel forced or to move anything to the community or to add carthage support. These can be done with issues and anyone can work on it. Why I suggested that you move it to the community is that you have more visibility and that will also help the community avoid duplicated frameworks just like this [RxLifeCycle](https://github.com/RxSwiftCommunity/contributors/issues/32) so think of it again and just that you know I will help in any carthage setup or whatsoever. Let's be a community
